module.exports = {
  CHAR_CREATE_IN_PROGRESS: 0x27,
  CHAR_CREATE_SUCCESS: 0x28,
  CHAR_CREATE_ERROR: 0x29,
  CHAR_CREATE_FAILED: 0x2a,
  CHAR_CREATE_NAME_IN_USE: 0x2b,
  CHAR_CREATE_DISABLED: 0x2c,
  LAST_CHAR_CREATE_RESULT: 0x2d
}
